set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

set(CMAKE_VERBOSE_MAKEFILE ON)

if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(OPENBCI_ARCHITECTURE "-32")
endif()

function(message)
    if(NOT OPENBCI_MESSAGE_QUIET)
        _message(${ARGN})
    endif()
endfunction()

if(MSVC)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING -D_CRT_NONSTDC_NO_DEPRECATE)

    # Set compiler options.
    set(variables
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_MINSIZEREL
        CMAKE_C_FLAGS_RELEASE
        CMAKE_C_FLAGS_RELWITHDEBINFO
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_MINSIZEREL
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_RELWITHDEBINFO
    )
endif()

if(MSVC)
    set(OPENBCI_LIBRARY_EXTENSION "dll")
elseif(APPLE)
    set(OPENBCI_LIBRARY_EXTENSION "dylib")
elseif(UNIX)
    set(OPENBCI_LIBRARY_EXTENSION "so")
endif()

include(FetchContent)