name: Clang Format

on: [push, pull_request]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: '.'
        exclude: './3rdparty ./modules/bglib/include/cmd_def.h ./modules/bglib/src/cmd_def.cpp'
        extensions: 'h,c,hpp,cpp'
        clangFormatVersion: 16
        inplace: False
