name: C/C++ Static Code Analysis

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install CppCheck
      run: |
        sudo -H apt-get update -y
        sudo -H apt-get install cppcheck
      env:
        DEBIAN_FRONTEND: noninteractive
    - name: Run Cppcheck
      run: cppcheck --std=c++20 --error-exitcode=1 --xml --xml-version=2 --force modules 2>cppcheck_results.xml
    - name: Generate Report
      if: ${{ failure() }}
      run: cppcheck-htmlreport --title=NativeSDK --file=cppcheck_results.xml --report-dir=report
    - name: Upload Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: report
